name: acl24-dialect-aware-bias-detection
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - cffi=1.16.0
  - charset-normalizer=3.3.1
  - cryptography=41.0.7
  - cuda-compiler=12.3.2
  - cuda-cudart=11.8.89
  - cuda-cuobjdump=12.3.101
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=12.3.101
  - cuda-libraries=11.8.0
  - cuda-nvcc=12.3.107
  - cuda-nvprune=12.3.101
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-opencl=12.3.101
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icu=73.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjitlink=12.3.101
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.24.4
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.0
  - pip=23.3.1
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.18
  - python_abi=3.8
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.10.0
  - tk=8.6.13
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - typing_extensions=4.9.0
  - urllib3=1.26.18
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.5
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - accelerate==0.26.1
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astroid==2.6.6
      - asttokens==2.4.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.13.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bitsandbytes==0.41.1
      - bleach==6.1.0
      - blis==0.7.11
      - cachetools==5.3.2
      - catalogue==2.0.10
      - certifi==2023.7.22
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cmake==3.27.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.1.4
      - confection==0.1.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - cymem==2.0.8
      - datasets==2.14.6
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepspeed==0.12.6
      - defusedxml==0.7.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - evaluate==0.4.1
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - fastapi==0.104.1
      - fastjsonschema==2.18.1
      - fire==0.5.0
      - fonttools==4.43.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.59.0
      - h11==0.14.0
      - hjson==3.1.0
      - httptools==0.6.1
      - huggingface-hub==0.17.3
      - humanfriendly==10.0
      - icecream==2.1.3
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - iniconfig==2.0.0
      - ipykernel==6.26.0
      - ipython==8.12.3
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - isort==5.12.0
      - jedi==0.19.1
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.5.0
      - jupyter-core==5.4.0
      - jupyter-events==0.8.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.9.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.7
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - lazy-object-proxy==1.9.0
      - lit==17.0.4
      - markdown==3.5
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.6
      - mccabe==0.6.1
      - mistune==3.0.2
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.10
      - mypy==0.991
      - mypy-extensions==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - ninja==1.11.1.1
      - nltk==3.8.1
      - notebook-shim==0.2.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - openai==0.28.1
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - pkgutil-resolve-name==1.3.10
      - pluggy==1.3.0
      - preshed==3.0.9
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.4
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.13
      - pydantic-core==2.10.1
      - pygments==2.16.1
      - pylint==2.8.2
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - pytest==7.4.3
      - pytest-asyncio==0.21.1
      - pytest-forked==1.6.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyzmq==25.1.1
      - ray==2.8.0
      - referencing==0.30.2
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rouge-score==0.1.2
      - rpds-py==0.10.6
      - rsa==4.9
      - safetensors==0.4.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.0
      - send2trash==1.8.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.33.1
      - seqeval==1.2.2
      - setproctitle==1.3.3
      - six==1.16.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - stack-data==0.6.3
      - starlette==0.27.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.3.0
      - terminado==0.17.1
      - thinc==8.2.1
      - threadpoolctl==3.2.0
      - tiktoken==0.5.1
      - tinycss2==1.2.1
      - tokenizers==0.14.1
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.0.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.12.0
      - transformers==4.34.1
      - triton==2.0.0
      - typer==0.9.0
      - types-python-dateutil==2.8.19.14
      - types-pyyaml==6.0.12.12
      - types-requests==2.31.0.10
      - types-setuptools==68.2.0.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - vllm==0.2.1.post1
      - wasabi==1.1.2
      - watchfiles==0.21.0
      - wcwidth==0.2.8
      - weasel==0.3.3
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - wrapt==1.12.1
      - xformers==0.0.22
      - xxhash==3.4.1
      - yapf==0.32.0
      - yarl==1.9.2
      - zipp==3.17.0
